### PR TITLE
Parsed incoming twitter word correctly

### PR DESCRIPTION
**Pull request by itpun**
Fixed the twitter correction reply so that the word is first parsed to make sure there are no special characters at the end of it. Not made to be abused tbh.

### CODE REVIEW

**Comment by omajid** [comment]
Unit test please?

**Comment by itpun** [comment]
@omajid did you mean an explanation on how to test this?

**Comment by omajid** [comment]
No. I would like to see a unit test exercising this code and verifying that corner cases are handled correctly :)

**Comment by itpun** [comment]
I'm merging the twitter command for now, I think the junit setup should be its own issue (which I've logged). It's going to need to set up its on temp redis server in order to do so.

**Comment by omajid** [comment]
@itpun Redis for unit tests? I mean unit tests as small isolated tests to verify specific functionality. End-to-end integration tests would be nice to have but that wasn't my request.

**Comment by itpun** [comment]
Pull request #54 hopefully is what you are looking for. Sorry, somehow thought you were thinking about something much larger :D

**Comment by omajid** [comment]
Thanks! Great to have tests :)

**Pull request merged**
