### PR TITLE
Limits number of facts/quotes printed with dump -> Random5 and Print number of quotes/facts

### PR DESCRIPTION
**Pull request by onyiny-ang**
Particular entries in the database have come to have a large amount of facts/quotes associated with them. It is hard on Vilebot1 when these people are quote/fact dumped and often causes significant lag in Vilebot's response time.
This is not a perfect solution but should offer some relief. This will pull 5 random quotes/facts from a user's database and print them. There is not, however, a check for whether these are the same 5 random quotes/facts so it is possible that the same 5 quotes could be printed on any given call of the quote/fact dump command. Still, I think this is better than the current model!

### CODE REVIEW

**Comment by justinmcook** [comment]
Thanks for this, looks good!

**Comment by aptmac** [comment]
I don't have a problem with shortening the number of results (that's probably a good thing), but I think this kind of changes the functionality of a "quote dump". 

Perhaps we could explore some kind of pseudo-pagination-like functionality? Like if I have 50 quotes Vilebot could return the first 10 and let me know that I have 4 "pages" of unread quotes left, and could fetch quotes 11-20 on page 2, 21-30 on page 3, etc. Maybe some command like `!quotedump <user> --page 2`.

**Comment by Josh-Matsuoka** [comment]
+1 To Alex's suggestion. A valid and (at least for me) fairly common use case of !quotedump and !factdump is if you're looking for a particular quote/fact but can't remember enough details to !quotesearch or !factsearch it. In those cases you could end up !quotedump/!factdumping for a while waiting for it to randomly appear.

I think pagination would be a good way to preserve those use cases while solving the current issue.

**Comment by aptmac** [comment]
@onyiny-ang is the lag from quotedump actually from retrieving the data from the DB, or is it from VileBot having to write them out? It is unfortunate that the data comes back in a set .. but potentially having a function to dump all the quotes and then return a sub-set with some "pagination" may work (even though it's complete overkill in some situations). I was just more concerned about the case that @Josh-Matsuoka brought up, where if I'm fishing for a quote someone said but don't remember enough about it to quotesearch then I may end up with VileBot returning more lines than actual quotes by the time I find it.

**Comment by omajid** [comment]
*cough* tests *cough*

**Comment by onyiny-ang** [comment]
@aptmac I believe that the lag is due to Vilebot having to print them out.The set of quotes/facts was the first thing collected in the original command and no matter how many quotes a "noun" had, Vilebot would respond quickly with the first few quotes/facts. It's only when it's iterating through 7+ quotes or so that it starts to slows down, which seems to suggest the initial retrieval of quotes/facts isn't the issue.

**Comment by onyiny-ang** [comment]
After talking with @justinmcook, I've decided to adjust the scope of this PR to add commands to print the number of facts/quotes a user has and to print a random 5 quotes/facts of a user. These can be accessed with `!( quote | fact )number noun` and `!(quote | fact )random5 noun`. @justinmcook has another idea to improve the ( quote | fact )dump situation which I think will work. Expect a new PR from him soon and keep the great reviews coming!

**Pull request merged**
