### PR TITLE
Fix quote/fact display for church

### PR DESCRIPTION
**Pull request by yuqi-zhang**
The 4th donor now has proper "title" display for quotes and facts.

### CODE REVIEW

**Comment by yuqi-zhang** [comment]
Fixes https://github.com/oldterns/VileBot/issues/55
@itpun

**Comment by omajid** [comment]
*cough* unit test *cough*

**Comment by yuqi-zhang** [comment]
I think its probably better to create unit tests for the whole church section and not just one test for this case. That will probably take awhile and should probably be a separate PR.

As for refactoring of the expression, I think it makes sense to have a method in church called is_top_donor, good call.

**Comment by justinmcook** [comment]
Closing due to #139 fixing this issue

**Pull request closed without merging**
