### PR TITLE
Preventing duplicate karma in one line, disallow self fact/quote adding

### PR DESCRIPTION
**Pull request by WChrisK**

### CODE REVIEW

**Comment by Josh-Matsuoka** [comment]
Self quoting and factadding can be debated, but I don't think multiline karma is an issue, I think its a fully intended part of the feature.

**Comment by itpun** [comment]
@Josh-Matsuoka having it as a Hashset will only prevent multiline karma with duplicates, which i think is fair

**Comment by WChrisK** [comment]
Is updating the name of this sufficient?

**Comment by WChrisK** [comment]
Hopefully that is more clear, however if you have an idea you have full permission to edit it to whatever you want

**Comment by itpun** [comment]
works for me. Approved.

**Pull request merged**
