### PR TITLE
Fixes bug causing Jeopardy to not work

### PR DESCRIPTION
**Pull request by justinmcook**
The bug breaking jeopardy was caused by invalidFlag always getting set (not sure why this was happening), so removing invalidFlag fixed the issue. Also added a check to prevent infinite recursion when question is constantly returned as being empty.
Fixes https://github.com/oldterns/VileBot/issues/94

### CODE REVIEW

**Comment by omajid** [comment]
2 suggestions. Not because I particularly care about this piece of code, but because I want you to get better.

> (not sure why this was happening)

Every time you think this, you should really look into the code again. You could be missing something very important about the code. Take a look at the git history to see how the changes were made for additional context.

> Also added a check to prevent infinite recursion when question is constantly returned as being empty

Could I convince you to add a unit test to prove to a future maintainer that your implementation works as designed and isn't broken?

**Comment by justinmcook** [comment]
> Every time you think this, you should really look into the code again
Relooked at the code and changed it (apparently the JSON object had null as a string and that was causing the issue)

> Could I convince you to add a unit test
Sure, I'll add one once I have some time sometime this week (maybe tonight)

**Comment by justinmcook** [comment]
@omajid 
Added test coverage for being in the wrong channel causes failure and test coverage for being in the right channel starts jeopardy. I don't think it is possible to add test coverage for infinite recursion and that it accepts the right answer without further modifying Trivia.java (if it is even possible to add test coverage for those)

**Comment by omajid** [comment]
Thanks!

**Pull request merged**
