### PR TITLE
Replace keratin-irc with PircBotX

### PR DESCRIPTION
**Pull request by salmanfs815**
Change IRC framework to [PircBotX](https://github.com/pircbotx/pircbotx/).
Reasons for change:
- keratin-irc is outdated whereas pircbotx is in active development
- pircbotx is more feature-rich
- greater stability
- prevent excess flood (`!quotedump matthew` x 3), etc.

### CODE REVIEW

**Comment by ASzc** [comment]
Original pre-opensource VileBot was based on PircBot. I rewrote it and Keratin at the same time to fix a lot of the flaws with PircBot.

If you're having problems with Keratin, I can try to fix them.

**Comment by salmanfs815** [comment]
> Original pre-opensource VileBot was based on PircBot. I rewrote it and Keratin at the same time to fix a lot of the flaws with PircBot.

PircBotX is also a fork of PircBot.

> If you're having problems with Keratin, I can try to fix them.

I suppose the most prominent issue has been the bot not being able to throttle messages causing the socket to flood and break the connection.

**Comment by wongma7** [comment]
:-1: the bot just spaces out every message by what feels like a whole second. Excess flood is the server working as intended, it doesn't necessarily mean the bot is broken. Maybe there is potential for a user to prevent the bot from reconnecting by getting it disconnected enough but I doubt it'll ever happen, depends how evil users are & how the server is configured I guess. The spam from this lousy form of flood protection is far more abusable and annoying. IMO it is fine to leave the bot as is. Or a better flood protection solution needs to be found

**Comment by ASzc** [comment]
Missed your reply @salmanfs815, sorry.

As far as I remember, keratin just pushes the messages out as fast as it can, and the IRC server applies the rate limiting on its end. The original VileBot features were written to try to work within that limit, i.e. minimal line count, like in the help command. I never saw a disconnect due to this back when I ran it.

I think some of the commands that have been added more recently don't minimize line count. One solution would be to have these spammy commands output via a different connection, using sendPrivmsgAs (see `!lessweather`'s implementation). In theory you could even bypass the 1 message per second hard server limit that way.

**Comment by wongma7** [comment]
TY @salmanfs815 for implementing my super creative, elegant, intuitive, pastebin idea, (best idea I have ever had at Red Hat, my magnum opus, please merge it and let it be my legacy TY). I will remove my rude :-1: for now (although IDK anything about the other keratin->pircbotx changes here I just want my idea merged TY).

**Pull request merged**
