### PR TITLE
Add inquisit command

### PR DESCRIPTION
**Pull request by yuqi-zhang**
Add ability to start an inquisition vote against a church member
with !inquisit. This vote can only be invoked and passed by a
top 4 member.

### CODE REVIEW

**Comment by emmettu** [comment]
geez.

**Comment by yuqi-zhang** [comment]
geez indeed

**Comment by emmettu** [comment]
why is this not merged.

**Comment by emmettu** [comment]
what is going on.

**Comment by itpun** [comment]
Not in the office, will merge tomorrow

**Comment by yuqi-zhang** [comment]
I also didn't think "geez" counted as a review+

**Pull request merged**
