### PR TITLE
Enforce code format at the Maven level

### PR DESCRIPTION
**Pull request by Christopher-Chianelli**
Addresses #88. As shown by the MASSIVE commit size, a lot of the code does not follow format guidelines. This PR will force code to follow format guidelines (otherwise the build will fail).

### CODE REVIEW

**Comment by onyiny-ang** [comment]
Thanks for this PR. Could you also added the `mvn format` command to the travis.yml script? That will test the formatting in the PR build and fail if a person hasn't run mvn locally.

**Comment by Christopher-Chianelli** [comment]
@onyiny-ang No need, it already does that. It runs the "mvn formatter:validate" on the vilebot submodule. (You can check the Travis log for this PR to verify this)

**Comment by onyiny-ang** [comment]
@Christopher-Chianelli Ah. That makes sense. Sorry, still not used to maven.

**Comment by onyiny-ang** [comment]
LGTM. Who am I to argue with maven eclipse code style? Anyone else care to weigh in?

**Comment by amisevsk** [comment]
Tempted to start a flame war over which java code style is best :)

**Pull request merged**
