### PR TITLE
Create new LimitCommand utility to create limits on amount of times a VileBot command can be used per time period and add it to Ascii

### PR DESCRIPTION
**Pull request by justinmcook**
Initially setting the default values as 2 messages per 5 minutes

### CODE REVIEW

**Comment by Josh-Matsuoka** [comment]
Looks good, maybe expand the tests to include the case where there are no remaining uses left, and perhaps one with a shorter timeout so you can test that limit commands accumulate charges as expected. (You should be able to create a test subclass to do this)

**Comment by justinmcook** [comment]
If I'm understanding correctly, I believe it does that already (currently modifies ascii to use the custom time period constructor to change the limit to 1 second, runs !ascii twice, tries a third, sees the max uses error, waits a second, retries running a third, and sees the correct output again)

**Comment by justinmcook** [comment]
The verify part for it looks a bit off since I couldn't get Mockito to do it nicely, so the 3 invocations includes the initial 2 and the retried 1

**Comment by salmanfs815** [comment]
The limit should only be enforced in #thefoobar, game channels and private messages shouldn't be restricted.

**Comment by justinmcook** [comment]
Changed to only be enforced in #thefoobar

**Pull request merged**
