### PR TITLE
Added Rock Paper Scissors game

### PR DESCRIPTION
**Pull request by Christopher-Chianelli**
Can someone please test this? For some reason my handler was never activated (Countdown was also not activated on my machine, but Jeopardy and OMGWord were).

### CODE REVIEW

**Comment by Josh-Matsuoka** [comment]
Hi Chris,

A few comments.

In general, a lot of the indentation is off. Please format this consistently.

+ * Countdown implementation based off of Trivia.java

s/Countdown/Rock, paper, scissors

((0 >= wager || wager > 10) && (senderKarma < wager || wager < 0))

For the purposes of this condition, wager > 10 is redundant. As long as the wager is positive the first condition will be satisfied. You should simplify this to if ((wager > 10 && senderKarma < wager) || (wager < 0)) if you want it to be invalid when using greater than the default wager but more karma than you have.

+		return  RED +"RPS RULES: \n" + RESET
+				+ "1) Dare someone to play rock paper scissors with you! \n" + RESET

is the second RESET really needed here? You've already reset the color on the previous line and never changed it on this one.

+ "2) Rock beats scissors, paper beats rocks, and scissors beat paper \n"

paper beats rock, and scissors beats paper*

+ "3) Winner gets the betted karma. If it is a tie, karma is returned. \n"

Winner gets the wagered karma*

+	private static final Pattern cancelPattern = Pattern.compile("^!rpscancel)");

This has a closing bracket but no open bracket. This pattern won't compile and is likely the reason your handler never gets called.

+			if (daredNick == "BazBot") {

This is going to compare references which probably isn't what you intended.

The game logic itself seems to be flawed. When I start a game and submit an answer it immediately ends before my opponent can submit one, resulting in situations like

11:33 < DMBot1> Jmatsuok dared almac 3 karma on a Rock Paper Scissors match.                                                                                                                       
11:33 < DMBot1> Use " /msg DMBot1 !(rock|paper|scissors) " to submit.                                                                                                                              
11:33 < DMBot1> Jmatsuok used rock, almacused null, almac takes 3 karma from Jmatsuok!  

In addition to this you're currently allowed to start a rock paper scissors game with yourself, This shouldn't be supported.

e.g. 
11:47 < almac> !rps almac 3                                                                                                                                                                       
11:47 < DMBot1> almac dared almac 3 karma on a Rock Paper Scissors match.                                                                                                                          
11:47 < DMBot1> Use " /msg DMBot1 !(rock|paper|scissors) " to submit.                                                                                                                                                                                                                                                                                           
11:47 < DMBot1> almac used paper, almacused null, almac takes 3 karma from almac!     

+		private boolean setSubmission(String contestant, String answer) throws Exception {
+		    if (contestant.equals(callerNick)) {
+		        if (null != callerAnswer) {
+		            throw new Exception("You have already submitted your answer!\n");
+		        }
+		        callerAnswer = answer;
+		        return null == daredAnswer;
+		    }

You use this as the condition to end the game. This requires one of the responses to be null to end the game! You also never reset currGame if the game finishes "naturally", so subsequent games can't be played without calling !rpscancel.

        if ((isPrivate(event) && inGameChannel(event))) {

This condition doesn't really make sense. You're checking that the message came from the game channel, and in a private message simultaneously?

private boolean inGameChannel(ReceivePrivmsg event) {
        String currChannel = event.getChannel();
        if (RPS_CHANNEL.equals(currChannel)) {
        ...
        }
        return true;
}

So we check if the game channel is correct, and even if its not we return true by default? Are you sure this logic is correct?

Cheers,

- Josh

**Comment by onyiny-ang** [comment]
As well as Josh's comments, and pending testing etc. we need to decide how this will be implemented wrt karma.
If karma is going to be used, I propose a randomized wager (between rock | paper | scissors) to limit cheating which could take place in myriad ways otherwise. If karma is not going to be used, what is? If it's just a game to see who wins, we don't really need a wager--OR, we could just allow for the wager to be a string: ex. !rps cchianel lunch. Then if cchianel loses rps, he owes me lunch. That might be fun.

Another idea that I had for expansion is to allow more than 1 person to play. I suppose this could look like daring several people OR it could just be an open rps option(?). The same rules would apply but would be extended. If I challenge 10 people to rps and I wager rock and everyone else wagers paper, I lose*10 (I buy lunch for 10 people?) on the other hand, if the wagers are reversed, I win*10 (I get lunch on 10 different occasions!). Of course there is more variability here too. Some could win, tie or lose against a single challenger which is fine and could be handled accordingly. This method is sometimes used in large groups where a winner needs to be determined. Everyone plays rps against one another and the winners carry-on until there is only 1 person left. Ties get to remain in the pool, only losers are kicked out each time. That could be a possible extension of rps that might be useful (like when determining the next vilebot maintainer)

**Comment by onyiny-ang** [comment]
also please edit: https://github.com/oldterns/VileBot/blob/master/vilebot/src/main/java/com/oldterns/vilebot/handlers/user/Help.java
accordingly

**Comment by itpun** [comment]
@Christopher-Chianelli i know this is old now, but would you be able to fix up a version that is at least testable if there is still intention to complete this?

**Comment by lberk** [comment]
Could we please have more specific commit messages?

**Comment by itpun** [comment]
@Christopher-Chianelli http://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html

**Comment by emmettu** [comment]
The fix commits should be squashed.

**Comment by amisevsk** [comment]
+1 for squashing.

**Comment by Josh-Matsuoka** [comment]
Hi Chris,

Thanks for the update! The game seems to be working for 2 players now. A few comments below.

`+ * Countdown implementation based off of Trivia.java`

s/Countdown/RockPaperScissors

'+	        if (caller.equals(currGame.getCaller()) || caller.equals(currGame.getDared())) {
+	            currGame = null;
+	        }'

This cancels the game, but it would be nice to have some confirmation that the game was cancelled.

'+			if (daredNick == "BazBot") {
+			    this.daredAnswer = answers[rand.nextInt(answers.length)];
+			}'

Perhaps a property in the VileBot config would be better here for flexibility, rather than hardcoding the bot name.

'+		if (rpsMatcher.matches() && correctChannel(event)) {
+		    try {
+		        startRPSGame(event, rpsMatcher.group(1));
+			}
+		    catch (Exception e) {
+		        event.reply(e.getMessage());
+		    }'

2 comments here; You should have a check to stop players from starting a rock-paper-scissors game with themselves, or if you want to support this make sure it works correctly. Currently if you do this the game never ends. Second, replying with the exception message is fine for debugging, but in production this should really be in the console.

Cheers,

- Josh

**Comment by Christopher-Chianelli** [comment]
@Josh-Matsuoka, the exception message wasn't used for debugging; it was a little trick I did to give error messages to the user when they try to do something illegal (changing your answer). I know nothing in the method could throw an Exception except when I throw one explicitly. I have implemented the rest of your changes, just going to tweak it a bit. (Don't worry, I'll squash to one commit)

**Comment by WChrisK** [comment]
Does anyone know if the eclipse style document requires spaces or tabs? The indentation in the commit looks like it changes all the time and makes reading it brutal. 

There are
- lines with 2 spaces
- lines with 2 tabs
- lines with 2 tabs and 4 spaces
- lines with all spaces
- lines with 2 tabs and 8 spaces
... etc

Both Eclipse and Intellij make this a one-click-option too by a 'Format code' menu option, plus this might take care of all the other formatting issues (which are too trivial to comment on IMO, but it'd be neat to see them fixed in one easy click) 

Also wondering:
`isPrivate(event) && inGameChannel(event)`
Does this mean the event is both a private message, and in a public game channel? Is that possible?

**Pull request merged**
